# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build package and demo app"
  lane :build do
    build_app(
      project: "SmartAsyncImageDemo.xcodeproj",
      scheme: "SmartAsyncImageDemo",
      configuration: "Debug",
      skip_package_ipa: true,   # important: avoids IPA packaging
      destination: "generic/platform=iOS Simulator"
    )
  end


  desc "Run package unit tests and gather coverage"
  lane :package_tests do
    repo_root = File.expand_path("../../..", __dir__)

    Dir.chdir(repo_root) do
      sh <<~CMD
        set -euo pipefail
        rm -rf TestResults.xcresult coverage xccov.json coverage.xml
        mkdir -p coverage

        xcodebuild test \
          -scheme SmartAsyncImage \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 17" \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults.xcresult
      CMD
    end
  end

  desc "Convert coverage"
  lane :coverage_xml do
    repo_root = File.expand_path("../../..", __dir__)

    Dir.chdir(repo_root) do
      sh <<~CMD
        set -euo pipefail
        xcresultparser \
          --output-format cobertura \
          --project-root "#{repo_root}" \
          TestResults.xcresult > coverage.xml

        echo "Generated coverage.xml"
        grep -m 3 'filename="' coverage.xml
      CMD
    end
  end
end
